from flask import Flask, jsonify, request, make_response, render_template
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

# In-memory database
abbreviations = {
    'HTML': 'HyperText Markup Language',
    'CSS': 'Cascading Style Sheets',
    'JS': 'JavaScript',
    'LOL': 'Laugh Out Loud',
    'API': 'Application Programming Interface',
    'PDF': 'Portable Document Format',
    'URL': 'Uniform Resource Locator',
    'VPN': 'Virtual Private Network',
    'HTTP': 'Hypertext Transfer Protocol',
    'AFK': 'Away From Keyboard',
    'ASAP': 'As Soon As Possible',
    'BFF': 'Best Friends Forever',
    'BRB': 'Be Right Back',
    'BTW': 'By The Way',
    'FAQ': 'Frequently Asked Questions',
    'FYI': 'For Your Information',
    'GG': 'Good Game',
    'GTG': 'Got To Go',
    'IDK': 'I Don\'t Know',
    'IMO': 'In My Opinion',
    'IRL': 'In Real Life',
    'JK': 'Just Kidding',
    'LMAO': 'Laughing My Ass Off',
    'LOL': 'Laugh Out Loud',
    'NP': 'No Problem',
    'OMG': 'Oh My God',
    'ROFL': 'Rolling On the Floor Laughing',
    'TTYL': 'Talk To You Later',
    'WTF': 'What The F***',
    'YW': 'You\'re Welcome',
    'AF': 'As F***',
    'ASL': 'Age, Sex, Location',
    'ATB': 'All The Best',
    'B4': 'Before',
    'BAE': 'Before Anyone Else',
    'BB': 'Bye Bye',
    'BC': 'Because',
    'BIO': 'Biography',
    'BR': 'Best Regards',
    'CUL8R': 'See You Later',
    'CYA': 'See Ya',
    'DAE': 'Does Anyone Else',
    'DIY': 'Do It Yourself',
    'DM': 'Direct Message',
    'ETA': 'Estimated Time of Arrival',
    'FB': 'Facebook',
    'FOMO': 'Fear Of Missing Out',
    'FTW': 'For The Win',
    'FWIW': 'For What It\'s Worth',
    'GF': 'Girlfriend',
    'GM': 'Good Morning',
    'GN': 'Good Night',
    'GR8': 'Great',
    'HAND': 'Have A Nice Day',
    'HF': 'Have Fun',
    'HMU': 'Hit Me Up',
    'ICYMI': 'In Case You Missed It',
    'IDC': 'I Don\'t Care',
    'ILY': 'I Love You',
    'IMHO': 'In My Humble Opinion',
    'IRL': 'In Real Life',
    'ISO': 'In Search Of',
    'JK': 'Just Kidding',
    'JSYK': 'Just So You Know',
    'K': 'Okay',
    'L8R': 'Later',
    'LMK': 'Let Me Know',
    'MCM': 'Man Crush Monday',
    'MT': 'Modified Tweet',
    'NBD': 'No Big Deal',
    'NVM': 'Never Mind',
    'OFC': 'Of Course',
    'OMW': 'On My Way',
    'OOTD': 'Outfit Of The Day',
    'OP': 'Original Poster',
    'PPL': 'People',
    'RN': 'Right Now',
    'ROFLMAO': 'Rolling On the Floor Laughing My Ass Off',
    'SMH': 'Shaking My Head',
    'SFW': 'Safe For Work',
    'TBH': 'To Be Honest',
    'TGIF': 'Thank God It\'s Friday',
    'TMI': 'Too Much Information',
    'TBT': 'Throwback Thursday',
    'TTYL': 'Talk To You Later',
    'TY': 'Thank You',
    'WB': 'Welcome Back',
    'WCW': 'Woman Crush Wednesday',
    'WDYM': 'What Do You Mean',
    'WYD': 'What You Doing',
    'YOLO': 'You Only Live Once',
    'ZZZ': 'Sleeping or Bored',
    '4EVA': 'Forever',
    'AFAIK': 'As Far As I Know',
    'AMA': 'Ask Me Anything',
    'BBL': 'Be Back Later',
    'BRH': 'Be Right Here',
    'BTDT': 'Been There, Done That',
    'BTT': 'Back To Topic',
    'CTA': 'Call To Action',
    'DIKU': 'Do I Know You',
    'EM': 'Email',
    'FBO': 'Facebook Official',
    'FTFY': 'Fixed That For You',
    'GRATZ': 'Congratulations',
    'HBD': 'Happy Birthday',
    'ICYMI': 'In Case You Missed It',
    'ILYSM': 'I Love You So Much',
    'IMNSHO': 'In My Not So Humble Opinion',
    'IMO': 'In My Opinion',
    'IRL': 'In Real Life',
    'ISTG': 'I Swear To God',
    'JFYI': 'Just For Your Information',
    'KOTD': 'Kicks Of The Day',
    'L8': 'Late',
    'LMFAO': 'Laughing My Freaking Ass Off',
    'LMK': 'Let Me Know',
    'LOLZ': 'Laughing Out Loud',
    'MIA': 'Missing In Action',
    'NAGI': 'Not A Good Idea',
    'NGL': 'Not Gonna Lie',
    'NM': 'Never Mind',
    'NVM': 'Never Mind',
    'OMG': 'Oh My God',
    'OOTD': 'Outfit Of The Day',
    'OP': 'Original Poster',
    'OT': 'Off Topic',
    'OTL': 'Out To Lunch',
    'POTD': 'Photo Of The Day',
    'ROFL': 'Rolling On the Floor Laughing',
    'ROTFL': 'Rolling On the Floor Laughing',
    'SMH': 'Shaking My Head',
    'SO': 'Significant Other',
    'SRSLY': 'Seriously',
    'TBH': 'To Be Honest',
    'TBT': 'Throwback Thursday',
    'TFW': 'That Feeling When',
    'TIL': 'Today I Learned',
    'TL;DR': 'Too Long; Didn\'t Read',
    'TMI': 'Too Much Information',
    'TTYL': 'Talk To You Later',
    'WBU': 'What About You',
    'WDYM': 'What Do You Mean',
    'WYD': 'What You Doing',
    'WYWH': 'Wish You Were Here',
    'XOXO': 'Hugs and Kisses',
    'YMMV': 'Your Mileage May Vary',
    'YOLO': 'You Only Live Once',
    'YW': 'You\'re Welcome',
    '404': 'Not Found',
    '911': 'Emergency',
    '2BZ4UQT': 'Too Busy For You, Cutie',
    '2FAB': 'Too Fabulous',
    '2G2BT': 'Too Good To Be True',
    '2M2H': 'Too Much To Handle',
    '2MI': 'Too Much Information',
    '2MORO': 'Tomorrow',
    '2NITE': 'Tonight',
    '4COL': 'For Crying Out Loud',
    '6Y': 'Sexy',
    '8': 'Cool',
    '10Q': 'Thank You',
    'ABT': 'About',
    'ACC': 'Account',
    'AD': 'Advertisement',
    'ADDY': 'Address',
    'ADMIN': 'Administrator',
    'ADV': 'Advice',
    'AGT': 'Agent',
    'AKA': 'Also Known As',
    'ALT': 'Alternative',
    'AM': 'Ante Meridiem (Before Noon)',
    'AMI': 'Am I',
    'APPT': 'Appointment',
    'APPS': 'Applications',
    'APR': 'April',
    'AUG': 'August',
    'AUSSIE': 'Australian',
    'AUTO': 'Automatic',
    'AVG': 'Average',
    'BA': 'Bachelor of Arts',
    'BAC': 'Bachelor of Arts and Science',
    'BCNU': 'Be Seeing You',
    'BEYOND': 'BYND',
    'BIO': 'Biography',
    'BIZ': 'Business',
    'BLD': 'Building',
    'BLVD': 'Boulevard',
    'BRO': 'Brother',
    'BRUH': 'Brother',
    'BS': 'Bachelor of Science',
    'BSC': 'Bachelor of Science',
    'BSMT': 'Basement',
    'BU': 'Business Unit',
    'C': 'See',
    'CA': 'California',
    'CAD': 'Canadian Dollar',
    'CAL': 'Calendar',
    'CAP': 'Capture',
    'CD': 'Compact Disc',
    'CEO': 'Chief Executive Officer',
    'CERT': 'Certificate',
    'CFM': 'Come Fly with Me',
    'CGI': 'Computer Generated Imagery',
    'CH': 'Child',
    'CHEEZ': 'Cheese',
    'CHK': 'Check',
    'CHP': 'California Highway Patrol',
    'CHR': 'Christmas',
    'CID': 'Criminal Investigation Department',
    'CL': 'Craigslist',
    'CLE': 'Certified Legal Executive',
    'CLOCK': 'CLCK',
    'CLS': 'Class',
    'CM': 'Centimeter',
    'CMD': 'Command',
    'CMOS': 'Complementary Metal-Oxide-Semiconductor',
    'CO': 'Colorado',
    'COM': 'Commercial',
    'COMP': 'Computer',
    'CON': 'Congratulations',
    'COS': 'Because',
    'CPA': 'Certified Public Accountant',
    'CPL': 'Cost Per Lead',
    'CPU': 'Central Processing Unit',
    'CR8': 'Create',
    'CRM': 'Customer Relationship Management',
    'CRO': 'Conversion Rate Optimization',
    'CS': 'Computer Science',
    'CSM': 'Customer Success Manager',
    'CSS': 'Cascading Style Sheets',
    'CT': 'Connecticut',
    'CTA': 'Call To Action',
    'CTO': 'Chief Technology Officer',
    'CTR': 'Click-Through Rate',
    'CV': 'Curriculum Vitae',
    'CVR': 'Conversion Rate',
    'CYMK': 'Cyan, Magenta, Yellow, Key (Black)',
    'CYS': 'See You Soon',
    'D': 'Day',
    'DA': 'Digital Artist',
    'DB': 'Database',
    'DC': 'Direct Current',
    'DDS': 'Doctor of Dental Surgery',
    'DE': 'Delaware',
    'DEETS': 'Details',
    'DEO': 'Director of Engineering',
    'DES': 'Design',
    'DF': 'Don\'t Forget',
    'DIY': 'Do It Yourself',
    'DM': 'Direct Message',
    'DMV': 'Department of Motor Vehicles',
    'DNS': 'Domain Name System',
    'DOB': 'Date of Birth',
    'DOC': 'Document',
    'DOE': 'Depends on Experience',
    'DOM': 'Document Object Model',
    'DOW': 'Day of the Week',
    'DR': 'Doctor',
    'DRM': 'Digital Rights Management',
    'DRY': 'Don\'t Repeat Yourself',
    'DSL': 'Digital Subscriber Line',
    'DTC': 'Direct-to-Consumer',
    'DTH': 'Direct to Home',
    'DTP': 'Desktop Publishing',
    'DVR': 'Digital Video Recorder',
    'EAP': 'Employee Assistance Program',
    'EC': 'E-commerce',
    'EDD': 'Estimated Delivery Date',
    'EDM': 'Electronic Dance Music',
    'EDT': 'Eastern Daylight Time',
    'EEE': 'Electrical and Electronics Engineering',
    'EOD': 'End of Day',
    'EOFY': 'End of Financial Year',
    'EOS': 'End of Service',
    'EOW': 'End of Week',
    'EPC': 'Earn Per Click',
    'EOD': 'End Of Day',
    'EP': 'Extended Play',
    'ERP': 'Enterprise Resource Planning',
    'ETA': 'Estimated Time of Arrival',
    'ETC': 'Et Cetera',
    'EU': 'European Union',
    'EUC': 'End User Computing',
    'EV': 'Electric Vehicle',
    'FAQ': 'Frequently Asked Questions',
    'FB': 'Facebook',
    'FBO': 'Facebook Official',
    'FC': 'Football Club',
    'FED': 'Federal Reserve System',
    'FF': 'Follow Friday',
    'FFS': 'For F***\'s Sake',
    'FIFO': 'First In, First Out',
    'FIT': 'Frequency, Intensity, Time',
    'FOMO': 'Fear Of Missing Out',
    'FORTE': 'FLCK',
    'FTFY': 'Fixed That For You',
    'FTP': 'File Transfer Protocol',
    'FTR': 'For The Record',
    'FWIW': 'For What It\'s Worth',
    'FYA': 'For Your Amusement',
    'FYEO': 'For Your Eyes Only',
    'FYI': 'For Your Information',
    'GA': 'Georgia',
    'GB': 'Gigabyte',
    'GD': 'Good',
    'GF': 'Girlfriend',
    'GG': 'Good Game',
    'GH': 'Gigahertz',
    'GIF': 'Graphics Interchange Format',
    'GIGO': 'Garbage In, Garbage Out',
    'GM': 'Good Morning',
    'GMT': 'Greenwich Mean Time',
    'GN': 'Good Night',
    'GOAT': 'Greatest Of All Time',
    'GP': 'General Practitioner',
    'GPS': 'Global Positioning System',
    'GR8': 'Great',
    'GTG': 'Got To Go',
    'GUI': 'Graphical User Interface',
    'GURL': 'Girl',
    'GV': 'Google Voice',
    'H': 'Hour',
    'HA': 'High Availability',
    'HB': 'Hug Back',
    'HBD': 'Happy Birthday',
    'HC': 'Hardcore',
    'HD': 'High Definition',
    'HEA': 'Happily Ever After',
    'HH': 'Handheld',
    'HMD': 'Head-Mounted Display',
    'HMU': 'Hit Me Up',
    'HOT': 'Hawt',
    'HP': 'Hewlett-Packard',
    'HR': 'Human Resources',
    'HRH': 'His/Her Royal Highness',
    'HT': 'Heard Through',
    'HTML': 'HyperText Markup Language',
    'HTTP': 'Hypertext Transfer Protocol',
    'HTTPS': 'Hypertext Transfer Protocol Secure',
    'HW': 'Homework',
    'I18N': 'Internationalization',
    'IA': 'Iowa',
    'IC': 'I See',
    'IDC': 'I Don\'t Care',
    'IDE': 'Integrated Development Environment',
    'IDK': 'I Don\'t Know',
    'IE': 'Internet Explorer',
    'IG': 'Instagram',
    'IGTV': 'Instagram TV',
    'ILY': 'I Love You',
    'IM': 'Instant Message',
    'IMHO': 'In My Humble Opinion',
    'IMS': 'IP Multimedia Subsystem',
    'INC': 'Incorporated',
    'INFO': 'Information',
    'INTERNET': 'INT',
    'INTL': 'International',
    'IOU': 'I Owe You',
    'IQ': 'Intelligence Quotient',
    'IR': 'Infrared',
    'IRL': 'In Real Life',
    'IS': 'Information Systems',
    'ISO': 'International Organization for Standardization',
    'ISS': 'International Space Station',
    'IT': 'Information Technology',
    'ITS': 'It Is',
    'IWSN': 'I Want Sex Now',
    'J': 'Just',
    'JA': 'Just Asking',
    'JAN': 'January',
    'JAVA': 'JAV',
    'JC': 'Just Curious',
    'JD': 'Juris Doctor',
    'JIT': 'Just-In-Time',
    'JK': 'Just Kidding',
    'JP': 'Japan',
    'JPN': 'Japanese',
    'JST': 'Japan Standard Time',
    'JV': 'Joint Venture',
    'JVM': 'Java Virtual Machine',
    'K': 'OK',
    'K8S': 'Kubernetes',
    'KB': 'Kilobyte',
    'KDR': 'Kill-Death Ratio',
    'KEK': 'LOL in Korean',
    'KEY': 'QLTY',
    'KF': 'Kentucky Fried',
    'KK': 'OK, Cool',
    'KM': 'Kilometer',
    'KNOW': 'KNO',
    'KO': 'Knock Out',
    'KPI': 'Key Performance Indicator',
    'L': 'Later',
    'LA': 'Los Angeles',
    'LAPTOP': 'LTP',
    'LBS': 'Pounds',
    'LC': 'Low Cost',
    'LED': 'Light-Emitting Diode',
    'LEGIT': 'Legitimate',
    'LEMME': 'Let Me',
    'LIEK': 'Like',
    'LMAO': 'Laughing My Ass Off',
    'LMK': 'Let Me Know',
    'LOL': 'Laugh Out Loud',
    'LP': 'Long Play',
    'LTE': 'Long-Term Evolution',
    'LUV': 'Love',
    'LYK': 'Let You Know',
    'M8': 'Mate',
    'MA': 'Massachusetts',
    'MAGA': 'Make America Great Again',
    'MBA': 'Master of Business Administration',
    'MBPS': 'Megabits Per Second',
    'MCS': 'Master of Computer Science',
    'MD': 'Doctor of Medicine',
    'ME': 'Maine',
    'MED': 'Medical',
    'METH': 'METHamphetamine',
    'MIA': 'Missing In Action',
    'MIKE': 'MikeEcho',
    'MIL': 'Mother-in-Law',
    'MIN': 'Minute',
    'MISC': 'Miscellaneous',
    'MK': 'Mark',
    'MKAY': 'Okay',
    'MLM': 'Multi-Level Marketing',
    'MM': 'Millimeter',
    'MO': 'Missouri',
    'MOD': 'Modification',
    'MOM': 'Moment',
    'MOMENT': 'MMNT',
    'MORO': 'More',
    'MSG': 'Message',
    'MT': 'Mountain',
    'MTD': 'Month to Date',
    'MTG': 'Meeting',
    'MTL': 'Montreal',
    'MTN': 'Mountain',
    'MTR': 'Meter',
    'MUAH': 'Kiss',
    'MUZIK': 'Music',
    'MYOB': 'Mind Your Own Business',
    'N': 'And',
    'N2M': 'Not Too Much',
    'N8': 'Night',
    'NAP': 'Not A Problem',
    'NBD': 'No Big Deal',
    'NE': 'Nebraska',
    'NE1': 'Anyone',
    'NEVA': 'Never',
    'NFG': 'No F***ing Good',
    'NH': 'New Hampshire',
    'NI': 'No Idea',
    'NICE': 'NIS',
    'NIMBY': 'Not In My Backyard',
    'NIT': 'Not In Team',
    'NME': 'Enemy',
    'NMH': 'Not Much Here',
    'NMP': 'Not My Problem',
    'NNTR': 'No Need To Reply',
    'NOOB': 'Newbie',
    'NOS': 'Nitrous Oxide Systems',
    'NP': 'No Problem',
    'NQOCD': 'Not Quite Our Class, Dear',
    'NRG': 'Energy',
    'NSA': 'National Security Agency',
    'NSFW': 'Not Safe For Work',
    'NSN': 'Non-Sufficient Funds',
    'NSO': 'National Security Office',
    'NT': 'No Thanks',
    'NTS': 'Note To Self',
    'NTT': 'Need To Talk',
    'NVM': 'Never Mind',
    'NW': 'Northwest',
    'NWOT': 'New Without Tags',
    'NWR': 'Not Work Related',
    'NY': 'New York',
    'NYC': 'New York City',
    'O': 'Oh',
    'OBV': 'Obviously',
    'OD': 'Overdose',
    'OH': 'Ohio',
    'OIC': 'Oh, I See',
    'OM': 'Oh My',
    'OMB': 'Oh My Buddha',
    'OMDB': 'Oh My Dear Buddha',
    'OMFG': 'Oh My F***ing God',
    'OMG': 'Oh My God',
    'OMW': 'On My Way',
    'ONTO': 'ON2',
    'OO': 'Out Of',
    'OOTD': 'Outfit Of The Day',
    'OP': 'Original Poster',
    'OPE': 'Opening',
    'ORLY': 'Oh, Really?',
    'OS': 'Operating System',
    'OSE': 'Operating System Environment',
    'OT': 'Off Topic',
    'OTL': 'Out to Lunch',
    'OTP': 'One True Pairing',
    'OW': 'Overwatch',
    'P': 'Problem',
    'PA': 'Pennsylvania',
    'PANIC': 'PANC',
    'PC': 'Personal Computer',
    'PD': 'Police Department',
    'PDF': 'Portable Document Format',
    'PENIS': 'Pen Is',
    'PG': 'Parental Guidance',
    'PHP': 'PHP: Hypertext Preprocessor',
    'PIC': 'Picture',
    'PLS': 'Please',
    'PLZ': 'Please',
    'PM': 'Private Message',
    'PO': 'Purchase Order',
    'POC': 'Proof of Concept',
    'POS': 'Piece of S***',
    'PPL': 'People',
    'PPM': 'Parts Per Million',
    'PPV': 'Pay-Per-View',
    'PR': 'Public Relations',
    'PRO': 'Professional',
    'PROB': 'Problem',
    'PROD': 'Production',
    'PROF': 'Professor',
    'PROMO': 'Promotion',
    'PROS': 'Professionals',
    'PRT': 'Party',
    'PS': 'Postscript',
    'PSA': 'Public Service Announcement',
    'PT': 'Physical Therapy',
    'PTO': 'Paid Time Off',
    'PTS': 'Points',
    'PU': 'That Stinks',
    'QA': 'Quality Assurance',
    'QC': 'Quality Control',
    'QOS': 'Quality Of Service',
    'QQ': 'Crying',
    'QR': 'Quick Response',
    'QSL': 'Reply',
    'QT': 'Cutie',
    'R': 'Are',
    'RA': 'Resident Assistant',
    'RAD': 'Radical',
    'RANK': 'RNK',
    'RBF': 'Resting Bitch Face',
    'RBI': 'Runs Batted In',
    'RBL': 'Real-Time Blackhole List',
    'RBTL': 'Read Between The Lines',
    'RDA': 'Recommended Daily Allowance',
    'RDO': 'Regular Day Off',
    'RE': 'Reply',
    'REF': 'Reference',
    'REKT': 'Wrecked',
    'REPO': 'Repossessed',
    'RES': 'Reservation',
    'RFI': 'Request For Information',
    'RFP': 'Request For Proposal',
    'RFC': 'Request For Comments',
    'RNG': 'Random Number Generator',
    'ROFL': 'Rolling On the Floor Laughing',
    'ROFLMAO': 'Rolling On the Floor Laughing My Ass Off',
    'ROFLMFAO': 'Rolling On the Floor Laughing My F***ing Ass Off',
    'ROFLMFAOO': 'Rolling On the Floor Laughing My F***ing Ass Off',
    'ROTFL': 'Rolling On the Floor Laughing',
    'ROTFLMAO': 'Rolling On the Floor Laughing My Ass Off',
    'ROTFLMFAO': 'Rolling On the Floor Laughing My F***ing Ass Off',
    'RSN': 'Real Soon Now',
    'RT': 'Retweet',
    'RTFM': 'Read The F***ing Manual',
    'RTM': 'Read The Manual',
    'RU': 'Are You',
    'RUB': 'Russian Ruble',
    'RWD': 'Responsive Web Design',
    'RYT': 'Right',
    'S': 'Smile',
    'SA': 'Société Anonyme',
    'SAD': 'Seasonal Affective Disorder',
    'SAG': 'Screen Actors Guild',
    'SAL': 'Salary',
    'SAT': 'Scholastic Aptitude Test',
    'SAY': 'Say',
    'SC': 'South Carolina',
    'SCM': 'Supply Chain Management',
    'SCNR': 'Sorry, Could Not Resist',
    'SD': 'South Dakota',
    'SE': 'Search Engine',
    'SEC': 'Securities and Exchange Commission',
    'SEK': 'Swedish Krona',
    'SELFIE': 'Self-Portrait',
    'SEO': 'Search Engine Optimization',
    'SERP': 'Search Engine Results Page',
    'SF': 'San Francisco',
    'SH': 'Sh**',
    'SHELFIE': 'Self-Portrait with Books',
    'SHH': 'Shhh',
    'SHR': 'Share',
    'SIL': 'Sister-In-Law',
    'SIS': 'Sister',
    'SMDH': 'Shaking My Damn Head',
    'SMEXI': 'Smart and Sexy',
    'SMFH': 'Shaking My F***ing Head',
    'SMILE': 'Smile',
    'SMIZE': 'Smile with Your Eyes',
    'SMS': 'Short Message Service',
    'SNL': 'Saturday Night Live',
    'SNS': 'Social Networking Service',
    'SOL': 'Sh** Out of Luck',
    'SOP': 'Standard Operating Procedure',
    'SOS': 'Save Our Souls',
    'SOW': 'Statement Of Work',
    'SPOC': 'Single Point of Contact',
    'SRSLY': 'Seriously',
    'SSDD': 'Same Stuff, Different Day',
    'SSN': 'Social Security Number',
    'STFU': 'Shut The F*** Up',
    'STONKS': 'Stocks',
    'STRM': 'Stream',
    'SUS': 'Suspicious',
    'SW': 'Software',
    'SYS': 'System',
    'T': 'Thank',
    'TA': 'Teaching Assistant',
    'TBA': 'To Be Announced',
    'TBH': 'To Be Honest',
    'TC': 'Take Care',
    'TIA': 'Thanks In Advance',
    'TID': 'Today I Discovered',
    'TIL': 'Today I Learned',
    'TL': 'Timeline',
    'TL;DR': 'Too Long; Didn\'t Read',
    'TM': 'Trademark',
    'TMI': 'Too Much Information',
    'TMW': 'That Moment When',
    'TN': 'Tennessee',
    'TOD': 'Time of Day',
    'TODAY': '2DAY',
    'TOEFL': 'Test of English as a Foreign Language',
    'TOTES': 'Totally',
    'TP': 'Toilet Paper',
    'TQ': 'Thank You',
    'TR': 'Turkey',
    'TRANSL8': 'Translate',
    'TRU': 'True',
    'TTC': 'Trying To Conceive',
    'TTYL': 'Talk To You Later',
    'TTYS': 'Talk To You Soon',
    'TURNT': 'Turned',
    'TW': 'Twitter',
    'TWEET': 'Twitter post',
    'TXT': 'Text',
    'U': 'You',
    'UC': 'University of California',
    'UCC': 'Uniform Commercial Code',
    'UD': 'Upstairs',
    'UFO': 'Unidentified Flying Object',
    'UGC': 'User-Generated Content',
    'UI': 'User Interface',
    'UK': 'United Kingdom',
    'UM': 'University of Michigan',
    'UN': 'United Nations',
    'UNI': 'University',
    'UR': 'Your',
    'URS': 'Yours',
    'US': 'United States',
    'USA': 'United States of America',
    'USB': 'Universal Serial Bus',
    'USER': 'USRI',
    'UTC': 'Coordinated Universal Time',
    'UWU': 'Happy Anime Face',
    'UX': 'User Experience',
    'V': 'Very',
    'VA': 'Virginia',
    'VACAY': 'Vacation',
    'VAT': 'Value Added Tax',
    'VBG': 'Very Big Grin',
    'VBS': 'Very Big Smile',
    'VIA': 'Via',
    'VIBE': 'Vibration',
    'VIP': 'Very Important Person',
    'VLOG': 'Video Log',
    'VM': 'Voice Mail',
    'VOIP': 'Voice Over Internet Protocol',
    'VPN': 'Virtual Private Network',
    'VPL': 'Visible Panty Line',
    'VS': 'Versus',
    'W': 'With',
    'WA': 'Washington',
    'WAKA': 'What Are You Doing',
    'WASSUP': 'What\'s Up',
    'WBU': 'What About You',
    'WC': 'Water Closet',
    'WCS': 'Worst Case Scenario',
    'WD': 'Well Done',
    'WED': 'Wednesday',
    'WEED': 'Cannabis',
    'WFH': 'Work From Home',
    'WHATEVS': 'Whatever',
    'WHY': 'World Hunger Year',
    'WI': 'Wisconsin',
    'WIFI': 'Wireless Fidelity',
    'WK': 'Week',
    'WKND': 'Weekend',
    'WOM': 'Word of Mouth',
    'WOMEN': 'WMN',
    'WOOHOO': 'Yay',
    'WORD': 'WRD',
    'WORK': 'WRK',
    'WOT': 'What',
    'WOW': 'World Of Warcraft',
    'WP': 'Well Played',
    'WRT': 'With Respect To',
    'WTF': 'What The F***',
    'WTG': 'Way To Go',
    'WTH': 'What The Hell',
    'WTH': 'What The Heck',
    'WU': 'What\'s Up',
    'WUP': 'What\'s Up',
    'WYD': 'What You Doing',
    'WYG': 'What You Got',
    'WYWH': 'Wish You Were Here',
    'X': 'Kiss',
    'XMAS': 'Christmas',
    'XOXO': 'Hugs and Kisses',
    'Y': 'Why',
    'YA': 'You',
    'YAY': 'Yeah',
    'YD': 'Yesterday',
    'YEAH': 'Yeah',
    'YH': 'Yeah',
    'YM': 'Your Mom',
    'YMCA': 'Young Men\'s Christian Association',
    'YOLO': 'You Only Live Once',
    'YR': 'Your',
    'YT': 'YouTube',
    'YW': 'You\'re Welcome',
    'Z': 'Zero',
    'ZAP': 'Zone of Absolute Proximity',
    'ZINE': 'Magazine',
    'ZIP': 'Zone Improvement Plan',
    'ZOMG': 'Oh My God',
    'ZOOM': 'Zoom In',
    'ZYXWVU': 'Zyxel Wireless Vpn Router',
    'MF': 'MotherFucker'
}
@app.route('/')
def index():
    return render_template('index.html')
# API endpoint to handle abbreviation requests
@app.route('/api/abbreviation/<abbr>')
def get_abbreviation(abbr):
    abbreviation = abbr.upper()
    full_name = abbreviations.get(abbreviation) or abbreviations.get(abbreviation.lower())

    if full_name:
        response = jsonify({'abbreviation': abbreviation, 'Meaning': full_name})
        response.headers.add('Access-Control-Allow-Origin', '*')
        return response
    else:
        return make_response(jsonify({'error': 'This entry does not exist in our records as of yet :( \n\n1. You can help us add this by creating a GitHub issue\n\n2. Or, you could fill out this feedback form and we will address the issue'}), 404)

# Start the server
if __name__ == '__main__':
    app.run( debug=True, port=5000)
